### ISSUE TITLE
Css assignment1   https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment1

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/Css#1]
https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment1

**Comment by ashubuddy89** [comment]
please check design again.
indentation issues.
Menu links are shifting when hover on the links.

**Comment by Abdul-Azeez** [comment]
Done please Check

**Comment by ashubuddy89** [comment]
Please remove extra gap between menus (home, about us etc).
Please check hover state of main menu link and drop-down in design.
Refer design - https://dl.dropboxusercontent.com/u/17934144/vtapp/exercise1.jpg

**Comment by Abdul-Azeez** [comment]
Please Check.

**Comment by Abdul-Azeez** [comment]
Please Check.

**Comment by ashubuddy89** [comment]
looking fine now..
