### ISSUE TITLE
css assignment2 : https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment2

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/Css#2]
https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment2

**Comment by ashubuddy89** [comment]
Please check design and instruction (Notes) again.

**Comment by Abdul-Azeez** [comment]
Done. Please confirm.

**Comment by Abdul-Azeez** [comment]
Done. Please re-check.

**Comment by ashubuddy89** [comment]
both section (left and right) must be similar in height when you increase the height of any section (content etc...)
currently if you increase content of left section. it'll not increase height of right section..

**Comment by Abdul-Azeez** [comment]
Done. Please re-check.

**Comment by ashubuddy89** [comment]
looking fine now...

**Comment by Abdul-Azeez** [comment]
Please Close.
