### ISSUE TITLE
css assignment 3  https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment3

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/Css#3]
https://github.com/Abdul-Azeez/Css/tree/master/cssAssignment3

**Comment by ashubuddy89** [comment]
Please check design again..
use "mailto" for sales@vinsol.com.
input text should be active (Focues) when you click on label.
radio button should be check when you click on label "Male and Female".

**Comment by Abdul-Azeez** [comment]
Done. Please Confirm.

**Comment by ashubuddy89** [comment]
looking fine now..
